# Generated by Django 6.1.1 on 2026-10-02 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('experience_level', models.CharField(choices=[('senior', 'Senior'), ('medium', 'Medium'), ('beginner', 'Beginner')], max_length=10)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('casual', 'Casual')], max_length=10)),
                ('active', models.BooleanField(default=True)),
                ('max_hours_per_week', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_staff', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Aisle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('department', models.CharField(max_length=100)),
                ('demand_level', models.CharField(choices=[('very_busy', 'Very busy'), ('medium', 'Medium'), ('quiet', 'Quiet')], max_length=10)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zone')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTaskSpeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('cage', 'Cage'), ('recovery', 'Recovery'), ('gap', 'Gap'), ('trolley', 'Trolley')], max_length=10)),
                ('speed', models.CharField(choices=[('fast', 'Fast'), ('medium', 'Medium'), ('slow', 'Slow')], max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('employee', 'task_type'), name='unique_employee_task_type')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField()),
                ('customer_speed', models.CharField(choices=[('fast', 'Fast'), ('medium', 'Medium'), ('slow', 'Slow')], max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employee')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skill')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('employee', 'skill'), name='unique_employee_skill')],
            },
        ),
    ]
