# Generated by Django 6.1.1 on 2026-10-07 13:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('expected_customers', models.IntegerField()),
                ('cages_waiting', models.IntegerField()),
                ('source', models.CharField(choices=[('manager_entered', 'Manager entered'), ('ml_predicted', 'ML predicted'), ('estimated', 'Estimated')], default='manager_entered', max_length=20)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zone')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('zone', 'date', 'hour'), name='unique_zone_date_hour')],
            },
        ),
    ]
