# Generated by Django 6.1.1 on 2026-10-07 13:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_demand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('task_type', models.CharField(choices=[('recovery', 'Recovery'), ('gap', 'Gap'), ('trolley', 'Trolley')], max_length=10)),
                ('minutes_required', models.IntegerField()),
                ('deadline_hour', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)])),
                ('source', models.CharField(choices=[('manager_entered', 'Manager entered'), ('estimated', 'Estimated'), ('ml_predicted', 'ML predicted')], default='manager_entered', max_length=20)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.zone')),
            ],
        ),
    ]
