# Generated by Django 6.1.1 on 2026-10-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_assignment'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('employee', 'date', 'hour'), name='unique_employee_date_hour'),
        ),
    ]
